<a href="https://colab.research.google.com/github/Ristika0726/Learning-machine-learning/blob/main/Numpy/class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#introdution to numpy
what we will cover today


*   Creating single dimensional arrays ✔️
*   Multidimensional arrays✔️
*   Randomly generated arrays✔️
*   Element wise operations✔️
*   Summarizing operations✔️



### Single dimensinal array
```
This is formatted as code
```

In [ ]:
import numpy as np
#creating
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#create an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array at of the size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
#create a random array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers within specified range
np.linspace(0,100, 11)
#np.linspace(0,100, 10)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###multi dimensional array 🦦


In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
#np.array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[2]=1 #by default understand its row
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
a[:, 2]=2
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
matrix=np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix=np.full((3,3), 10)
matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
matrix[:,:]=10
matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

###randomly generated arrays


*   NumPy can create arrays filled with random numbers
*   To ensure the reducibility, you can set a seed using ```np.random.seed()```. It will generate the exact smae random numbers for each executions
*   if you remove or change the seed values, the sequence of random numbers will be changed.






In [ ]:
np.random.rand(5)

array([0.75075624, 0.98349946, 0.77140553, 0.62174622, 0.15473486])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2) #follows normal distributions

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randn(2)

array([-1.00073842, -1.18248113])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[50, 46],
       [ 9, 24],
       [24,  1],
       [17, 54],
       [16, 41]])

##Elements wise operation on entire arrays element by element

In [ ]:
import numpy as np
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10+(a*2))
b

array([10, 12, 14, 16, 18])

In [ ]:
#comparison operations
a

array([0, 1, 2, 3, 4])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a > b

array([False, False, False, False, False])

In [ ]:
#summarization of data
#numpy provides function for summarizing array data
a


array([0, 1, 2, 3, 4])

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.max()

4

In [ ]:
a.min()

0

In [ ]:
a.sum()

10